NUnit
Assets\Mapbox\Unity\Tests\MapboxUnitTests_AbstractMapTests.cs(14,4): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)